### PR TITLE
Fix for blender 4.0 not loading materials

### PR DESCRIPTION
**Pull request by CFeeney333**
Blender 4.0s new principled BSDF node broke MCprep compatibility due to the renaming of sockets.
I added a blender version check and used the appropriate socket name to regain compatibility. Tested on blender 3.3.9 and blender 4.0.0 stable release, on linux.

### CODE REVIEW

**Comment by CFeeney333** [comment]
Am I able to link this pull request to an issue?
(#494)

**Comment by StandingPadAnimations** [comment]
Can't do a comprehensive review at the moment, but I've done a quick skim of the changes and it mostly looks good to me

**Review by TheDuckCow — APPROVED** [review]
Thank you for this quick fix! Working well locally.

All local tests passing:

```
------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(3.6.2)   	all_tests	64	2	0	No errors
(4.0.0)   	all_tests	64	2	0	No errors
(3.5.1)   	all_tests	64	2	0	No errors
(3.4.0)   	all_tests	64	2	0	No errors
(3.3.1)   	all_tests	64	2	0	No errors
(3.2.1)   	all_tests	64	2	0	No errors
(3.1.0)   	all_tests	64	2	0	No errors
(3.0.0)   	all_tests	64	2	0	No errors
(2.93.0)   	all_tests	63	3	0	No errors
(2.90.1)   	all_tests	63	3	0	No errors
(2.80.75)   	all_tests	62	4	0	No errors
tests took 273s to run, ending with code 0

```

**Comment by CFeeney333** [comment]
feck. never thought of transmission. Anyone else getting this?
image
(i have updated to 3.5.1)
will fix asap

**Comment by TheDuckCow** [comment]
Yeah that could be an oversight, we should create / update our unit tests to include some emission and other varieties of materials to make sure we have better scenario coverage. Will review any PR as soon as it comes through, then will decide when it makes sense to cut another release.

**Pull request merged**
