### PR TITLE
Set up new unittest system

### PR DESCRIPTION
**Pull request by TheDuckCow**
Currently, all two tests pass over all targeted versions of blender. See some different sample commands below (may eventually add this into a README, but that will be a later PR).

cmd: `python3 run_tests.py`
```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	failed	errors
-------------------------------------------------------------------------------
(3.6.0)   	all_tests	2	0	No errors
```

cmd: `python3 run_tests.py -a`
```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	failed	errors
-------------------------------------------------------------------------------
(3.6.0)   	all_tests	2	0	No errors
(3.5.1)   	all_tests	2	0	No errors
(3.4.0)   	all_tests	2	0	No errors
(3.2.1)   	all_tests	2	0	No errors
(3.3.1)   	all_tests	2	0	No errors
(3.1.0)   	all_tests	2	0	No errors
(3.0.0)   	all_tests	2	0	No errors
(2.93.0)   	all_tests	2	0	No errors
(2.90.1)   	all_tests	2	0	No errors
(2.80.75)   	all_tests	2	0	No errors
```

cmd: `python3 run_tests.py -t test_enable -v 3.6,2` (showing up running a specific test, and specific blender versions)
```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	failed	errors
-------------------------------------------------------------------------------
(3.6.0)   	test_enable	1	0	No errors
(2.93.0)   	test_enable	1	0	No errors
(2.90.1)   	test_enable	1	0	No errors
(2.80.75)   	test_enable	1	0	No errors
```

Relates to #424 but does not itself complete the change, as individual tests still need to be migrated.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
FYI that this isn't yet using the new build system, so in the meantime you'll have to modify the line:
`COMPILE_CMD = ["./compile.sh", "-fast"]` in the `run_tests.py` for now.

Once https://github.com/Moo-Ack-Productions/MCprep/pull/422 is merged, we'll update the script here.

**Comment by StandingPadAnimations** [comment]
I think I'm missing something, cause my output is barebones when running the test scripts. I did get the following error when running on Arch Linux, but it didn't seem to do much:
```sh
Failed to open dir (No such file or directory): /run/user/1000/gvfs/
```

`/run/user` is a Flatpak think so I don't know why that happened (since I'm using the native Blender package)

**Comment by TheDuckCow** [comment]
Happy to debug live in the later part of the dev team meeting in ~1h 45m, can you tell which line this is hailing from?

I realize that nothing stops you from trying to use the bpy-build command, if you want to locally swap for those args in the run_tests.py file `COMPILE_CMD` command args list.

**Comment by StandingPadAnimations** [comment]
> Happy to debug live in the later part of the dev team meeting in ~1h 45m, can you tell which line this is hailing from?

I'm not sure; doesn't impact much though. I'll test with `bpy-build` later today.

**Comment by TheDuckCow** [comment]
Any newfound luck with the latest bpy build structure @StandingPadAnimations? If not, I can separatley try to test on another machine in a fresh space.

**Comment by StandingPadAnimations** [comment]
Haven't tested with bpy-build yet, might try later today

**Comment by StandingPadAnimations** [comment]
Still get the error with `bpy-build` (had to do a local merge for `bpy-build`). Like I said, it doesn't seem to impact anything (and frankly it's a little confusing to me since I'm not running Blender as a Flatpak, but `/run` is normally associated with Flatpaks).

This is my test output:
```sh
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	failed	errors
-------------------------------------------------------------------------------
(3.6.0)   	all_tests	2	0	No errors
```

**Pull request merged**
