### PR TITLE
Remove MCprep optimizer

### PR DESCRIPTION
**Pull request by StandingPadAnimations**
The MCprep optimizer was deprecated in the MCprep 3.5 series, and slated for removal in MCprep 3.6. This is due to the following reasons:
- Outdated design (made prior to Blender 3.0 when Cycles X was still in development, and has yet to adapt to modern Cycles)
- Extreme bugs that are hard to fix, such as 80+ light bounces
- Unnecessary as there's no special optimizations for Minecraft scenes, and on the contrary may actually be a bad thing as it uses settings like clamping indirect with horrible options

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Are there any unit tests that should be removed as well? Would be good if you can post your current unit tests results, so far I think I've just been running them.

**Comment by TheDuckCow** [comment]
Also, seems like we need to merge in changes from dev to this branch for the new bpy build? getting errors on this branch while trying to build, but not when dev is checked out

```
Traceback (most recent call last):
  File "/Users/patrickcrawford/Documents/gits/mcprep/venv/bin/bpy-addon-build", line 8, in <module>
    sys.exit(main())
  File "/Users/patrickcrawford/Documents/gits/mcprep/venv/lib/python3.7/site-packages/bpy_addon_build/__init__.py", line 84, in main
    if len(yaml_conf.during_build):
AttributeError: 'BpyBuildYaml' object has no attribute 'during_build'
```

**Comment by StandingPadAnimations** [comment]
> Also, seems like we need to merge in changes from dev to this branch for the new bpy build? getting errors on this branch while trying to build, but not when dev is checked out
> 
> ```
> Traceback (most recent call last):
>   File "/Users/patrickcrawford/Documents/gits/mcprep/venv/bin/bpy-addon-build", line 8, in <module>
>     sys.exit(main())
>   File "/Users/patrickcrawford/Documents/gits/mcprep/venv/lib/python3.7/site-packages/bpy_addon_build/__init__.py", line 84, in main
>     if len(yaml_conf.during_build):
> AttributeError: 'BpyBuildYaml' object has no attribute 'during_build'
> ```
> 
> Hmm, same errors are present on the milestone branch, even though I just tried merging dev into that milestone. Not sure why those aren't in sync

I think you're using an older version of BpyBuild. BpyBuild 0.3.0 dropped Python 3.7 support

**Comment by TheDuckCow** [comment]
Whoops, yeah I somehow still had my 3.7 venv in my primary spot, forgot I had a duplicate of the mcprep git repo locally while we were working on the new builder.

Resetting up the virtual env, compiles fine now. As for this branch, all looking well:

```
-------------------------------------------------------------------------------
bversion   	ran_tests	ran	skips	failed	errors
-------------------------------------------------------------------------------
(3.6.2)   	all_tests	65	2	0	No errors
tests took 17s to run, ending with code 0
```

**Review by TheDuckCow — APPROVED** [review]

**Pull request merged**
