### PR TITLE
Milestone 3.6.0

### PR DESCRIPTION
**Pull request by StandingPadAnimations**
Merging MCprep 3.6 to dev

### CODE REVIEW

**Comment by StandingPadAnimations** [comment]
Before we merge, I just need to finish #548 and review #564

**Comment by TheDuckCow** [comment]
FYI https://github.com/Moo-Ack-Productions/MCprep/pull/564 is based on dev, so shouldn't cause any impact here. I'm going to approve this shortly, since all changes here have already been reviewed and approved before.

**Review by TheDuckCow — APPROVED** [review]

**Comment by StandingPadAnimations** [comment]
Alright, I'll merge this in now

**Comment by StandingPadAnimations** [comment]
I'll prepare a Release Candidate tomorrow. @TheDuckCow since I can't add tags on the repo, can you add tag `3.6.0-rc-1`?

**Comment by TheDuckCow** [comment]
Do you want me to tag the current state of dev then? And sure

**Comment by StandingPadAnimations** [comment]
> Do you want me to tag the current state of dev then? And sure

Yep :+1:

**Pull request merged**
